import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        canvas: "var(--bg)",
        surface: "var(--surface)",
        "surface-2": "var(--surface-2)",
        "surface-hover": "var(--surface-hover)",
        border: "var(--border)",
        "border-strong": "var(--border-strong)",
        divider: "var(--divider)",
        muted: {
          DEFAULT: "var(--muted)",
          foreground: "var(--muted-foreground)",
        },
        card: {
          DEFAULT: "var(--card)",
          foreground: "var(--card-foreground)",
        },
        popover: {
          DEFAULT: "var(--popover)",
          foreground: "var(--popover-foreground)",
        },
        primary: {
          DEFAULT: "var(--primary)",
          foreground: "var(--primary-foreground)",
        },
        secondary: {
          DEFAULT: "var(--secondary)",
          foreground: "var(--secondary-foreground)",
        },
        accent: {
          DEFAULT: "var(--accent)",
          hover: "var(--accent-hover)",
          active: "var(--accent-active)",
          foreground: "var(--accent-contrast)",
        },
        selection: {
          DEFAULT: "var(--selection)",
          foreground: "var(--selection-foreground)",
        },
        hover: "var(--hover)",
        active: "var(--active)",
        disabled: {
          DEFAULT: "var(--disabled)",
          foreground: "var(--disabled-foreground)",
        },
        input: {
          DEFAULT: "var(--input)",
          border: "var(--input-border)",
          "border-focus": "var(--input-border-focus)",
        },
        sidebar: {
          DEFAULT: "var(--sidebar)",
          foreground: "var(--sidebar-foreground)",
          accent: "var(--sidebar-accent)",
          "accent-foreground": "var(--sidebar-accent-foreground)",
          border: "var(--sidebar-border)",
          primary: "var(--sidebar-primary)",
          "primary-foreground": "var(--sidebar-primary-foreground)",
          ring: "var(--sidebar-ring)",
        },
        content: "var(--text)",
        "content-muted": "var(--text-muted)",
        "subtle-foreground": "var(--subtle-foreground)",
        "accent-contrast": "var(--accent-contrast)",
        danger: "var(--danger)",
        success: "var(--success)",
        overlay: "var(--overlay)",
        "shadow-color": "var(--shadow-color)",
        focus: "var(--focus-outline)",
        manus: {
          ink: "#34322D",
          mist: "#F8F8F8",
          paper: "#FFFFFF",
          inkA: {
            5: "rgba(52, 50, 45, 0.05)",
            8: "rgba(52, 50, 45, 0.08)",
            12: "rgba(52, 50, 45, 0.12)",
            16: "rgba(52, 50, 45, 0.16)",
            20: "rgba(52, 50, 45, 0.2)",
            40: "rgba(52, 50, 45, 0.4)",
            60: "rgba(52, 50, 45, 0.6)",
            80: "rgba(52, 50, 45, 0.8)",
          },
        },
      },
      fontFamily: {
        sans: ["var(--font-sans)"],
        serif: ["var(--font-serif)"],
        display: ["var(--font-display)"],
        mono: ["var(--font-mono)"],
      },
      fontSize: {
        xs: ["var(--text-xs)", { lineHeight: "var(--leading-tight)" }],
        sm: ["var(--text-sm)", { lineHeight: "var(--leading-tight)" }],
        base: ["var(--text-base)", { lineHeight: "var(--leading-normal)" }],
        lg: ["var(--text-lg)", { lineHeight: "var(--leading-normal)" }],
        xl: ["var(--text-xl)", { lineHeight: "var(--leading-tight)" }],
        "2xl": ["var(--text-2xl)", { lineHeight: "var(--leading-tight)" }],
      },
      lineHeight: {
        tight: "var(--leading-tight)",
        normal: "var(--leading-normal)",
        display: "var(--leading-display)",
      },
      letterSpacing: {
        display: "var(--tracking-display)",
      },
      borderRadius: {
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        panel: "var(--radius-panel)",
        card: "var(--radius-card)",
        hero: "var(--radius-hero)",
        prompt: "var(--radius-prompt)",
      },
      boxShadow: {
        sm: "var(--shadow-sm)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
        "manus-sm": "0 2px 12px rgba(52, 50, 45, 0.08)",
        manus: "0 12px 40px rgba(52, 50, 45, 0.12)",
        "manus-lg": "0 20px 60px rgba(52, 50, 45, 0.14)",
      },
      spacing: {
        1: "var(--space-1)",
        2: "var(--space-2)",
        3: "var(--space-3)",
        4: "var(--space-4)",
        5: "var(--space-5)",
        6: "var(--space-6)",
      },
      zIndex: {
        dropdown: "var(--z-dropdown)",
        dialog: "var(--z-dialog)",
        toast: "var(--z-toast)",
      },
    },
  },
  plugins: [],
};

export default config;
