import base64
import io
import json
import zipfile
from datetime import datetime, timezone
from uuid import UUID, uuid4

from fastapi import HTTPException
from app.routers import clients as clients_router
from app.db.enums import AssetSourceEnum
from app.db.models import Asset, Client, ShopifyThemeTemplateDraft, ShopifyThemeTemplateDraftVersion
from app.services.shopify_connection import ShopifyInstallation
from sqlalchemy import select


def _create_client(api_client, *, name: str = "Shopify Workspace") -> str:
    response = api_client.post("/clients", json={"name": name, "industry": "Retail"})
    assert response.status_code == 201
    return response.json()["id"]


def test_sanitize_theme_component_text_value_removes_unsupported_characters():
    raw_value = '  "Sleep <better>\n tonight\'s pick"  '
    assert (
        clients_router._sanitize_theme_component_text_value(raw_value)
        == "Sleep better tonight’s pick"
    )


def test_sanitize_theme_component_text_value_strips_inline_markup_tags():
    raw_value = "Boost <strong>energy</strong> and <em>focus</em> daily"
    assert (
        clients_router._sanitize_theme_component_text_value(raw_value)
        == "Boost energy and focus daily"
    )


def test_sanitize_theme_component_text_value_strips_block_html_tags():
    raw_value = (
        "<p>🌟 <strong>Our Mission</strong></p>"
        "<p>Bringing professional-grade LED light therapy to your home.</p>"
    )
    assert (
        clients_router._sanitize_theme_component_text_value(raw_value)
        == "🌟 Our Mission Bringing professional-grade LED light therapy to your home."
    )


def test_sanitize_theme_component_text_value_strips_orphan_closing_tag_fragments():
    raw_value = "Our Mission /em Bringing professional-grade LED therapy /strong to your home /p"
    assert (
        clients_router._sanitize_theme_component_text_value(raw_value)
        == "Our Mission Bringing professional-grade LED therapy to your home"
    )


def test_normalize_theme_export_text_file_content_rewrites_collection_test_links():
    normalized_content, rewritten_count = (
        clients_router._normalize_theme_export_text_file_content(
            filename="sections/custom-featured-collection.liquid",
            content=(
                '<a href="/collections/test">Shop</a>'
                '{"url":"/collections/test"}'
            ),
        )
    )
    assert rewritten_count == 2
    assert "/collections/test" not in normalized_content
    assert normalized_content.count("/collections/all") == 2


def test_validate_collection_template_component_values_in_export_accepts_collection_mappings():
    image_path = (
        "templates/collection.json.sections.main-collection.blocks.promotion.settings.image"
    )
    text_path = (
        "templates/collection.json.sections.main-collection.blocks.promotion.settings.heading"
    )
    collection_template_content = json.dumps(
        {
            "sections": {
                "main-collection": {
                    "blocks": {
                        "promotion": {
                            "settings": {
                                "image": "shopify://shop_images/promo.png",
                                "heading": "<p>Glow brighter</p>",
                            }
                        }
                    }
                }
            }
        }
    )

    report = clients_router._validate_collection_template_component_values_in_export(
        exported_text_files_by_filename={
            "templates/collection.json": collection_template_content
        },
        component_image_urls={image_path: "https://assets.example.com/public/assets/promo"},
        component_text_values={text_path: "Glow brighter"},
    )

    assert report == {
        "validatedImagePaths": [image_path],
        "validatedTextPaths": [text_path],
    }


def test_validate_collection_template_component_values_in_export_requires_template_file():
    image_path = (
        "templates/collection.json.sections.main-collection.blocks.promotion.settings.image"
    )
    try:
        clients_router._validate_collection_template_component_values_in_export(
            exported_text_files_by_filename={},
            component_image_urls={image_path: "https://assets.example.com/public/assets/promo"},
            component_text_values={},
        )
    except HTTPException as exc:
        assert exc.status_code == 422
        assert "templates/collection.json" in str(exc.detail)
    else:
        raise AssertionError(
            "Expected collection template validation to fail when templates/collection.json is missing"
        )


def test_validate_required_collection_templates_in_export_accepts_shopify_comment_wrapped_json():
    collection_template_content = (
        "/* Shopify autogenerated comment */\n"
        "{"
        '"sections":{"main-collection-banner":{"type":"main-collection-banner"},'
        '"main-collection":{"type":"main-collection"}}'
        "}"
    )
    list_collections_template_content = (
        "/* Shopify autogenerated comment */\n"
        '{"sections":{"main":{"type":"main-list-collections"}},"order":["main"]}'
    )

    report = clients_router._validate_required_collection_templates_in_export(
        exported_text_files_by_filename={
            "templates/collection.json": collection_template_content,
            "templates/list-collections.json": list_collections_template_content,
        }
    )

    assert sorted(report["validatedTemplates"]) == [
        "templates/collection.json",
        "templates/list-collections.json",
    ]
    assert "main-collection-banner" in report["validatedCollectionSections"]
    assert "main-collection" in report["validatedCollectionSections"]


def test_validate_required_collection_templates_in_export_requires_template_files():
    try:
        clients_router._validate_required_collection_templates_in_export(
            exported_text_files_by_filename={}
        )
    except HTTPException as exc:
        assert exc.status_code == 422
        assert "templates/collection.json" in str(exc.detail)
        assert "templates/list-collections.json" in str(exc.detail)
    else:
        raise AssertionError(
            "Expected missing required collection template files to fail validation"
        )


def test_build_theme_sync_image_slot_text_hints_uses_adjacent_feature_copy():
    feature_image_path = (
        "templates/index.json.sections.ss_feature_1_pro_MNXtYb.blocks.slide_47f4ep.settings.image"
    )
    hints = clients_router._build_theme_sync_image_slot_text_hints(
        image_slots=[
            {"path": feature_image_path},
            {"path": "templates/index.json.sections.hero.settings.image"},
        ],
        text_slots=[
            {
                "path": (
                    "templates/index.json.sections.ss_feature_1_pro_MNXtYb.blocks.slide_47f4ep."
                    "settings.title"
                ),
                "currentValue": "We deliver worldwide",
            },
            {
                "path": (
                    "templates/index.json.sections.ss_feature_1_pro_MNXtYb.blocks.slide_47f4ep."
                    "settings.text"
                ),
                "currentValue": "Fast <strong>shipping</strong> for all orders",
            },
            {
                "path": "templates/index.json.sections.hero.settings.heading",
                "currentValue": "Hero heading",
            },
        ],
    )

    assert hints == {
        feature_image_path: "We deliver worldwide Fast shipping for all orders"
    }


def test_normalize_asset_public_id_handles_uuid_and_string():
    uuid_value = UUID("11111111-1111-1111-1111-111111111111")
    assert clients_router._normalize_asset_public_id(uuid_value) == "11111111-1111-1111-1111-111111111111"
    assert clients_router._normalize_asset_public_id("  abc-123  ") == "abc-123"
    assert clients_router._normalize_asset_public_id("") is None
    assert clients_router._normalize_asset_public_id(None) is None


def test_get_shopify_status_returns_service_payload(api_client, monkeypatch):
    client_id = _create_client(api_client)

    observed: dict[str, str] = {}

    def fake_status(*, client_id: str, selected_shop_domain: str | None = None):
        observed["client_id"] = client_id
        return {
            "state": "ready",
            "message": "Shopify connection is ready.",
            "shopDomain": "example.myshopify.com",
            "shopDomains": [],
            "selectedShopDomain": selected_shop_domain,
            "hasStorefrontAccessToken": True,
            "missingScopes": [],
        }

    monkeypatch.setattr(clients_router, "get_client_shopify_connection_status", fake_status)

    response = api_client.get(f"/clients/{client_id}/shopify/status")

    assert response.status_code == 200
    assert observed["client_id"] == client_id
    assert response.json()["state"] == "ready"


def test_create_shopify_install_url_returns_url(api_client, monkeypatch):
    client_id = _create_client(api_client)

    observed: dict[str, str] = {}

    def fake_build(*, client_id: str, shop_domain: str) -> dict[str, str]:
        observed["client_id"] = client_id
        observed["shop_domain"] = shop_domain
        return {
            "installUrl": "https://shopify-public.local/auth/install?shop=example.myshopify.com&client_id=test",
        }

    monkeypatch.setattr(clients_router, "build_client_shopify_install_urls", fake_build)

    response = api_client.post(
        f"/clients/{client_id}/shopify/install-url",
        json={"shopDomain": "example.myshopify.com"},
    )

    assert response.status_code == 200
    assert observed == {"client_id": client_id, "shop_domain": "example.myshopify.com"}
    body = response.json()
    assert body["installUrl"].startswith("https://shopify-public.local/auth/install")


def test_update_shopify_installation_sets_token_and_returns_status(api_client, monkeypatch):
    client_id = _create_client(api_client)

    observed: dict[str, str] = {}

    def fake_set_token(*, client_id: str, shop_domain: str, storefront_access_token: str) -> None:
        observed["client_id"] = client_id
        observed["shop_domain"] = shop_domain
        observed["storefront_access_token"] = storefront_access_token

    def fake_status(*, client_id: str, selected_shop_domain: str | None = None):
        return {
            "state": "installed_missing_storefront_token",
            "message": "Shopify is installed but missing storefront access token.",
            "shopDomain": "example.myshopify.com",
            "shopDomains": [],
            "selectedShopDomain": selected_shop_domain,
            "hasStorefrontAccessToken": False,
            "missingScopes": [],
        }

    monkeypatch.setattr(clients_router, "set_client_shopify_storefront_token", fake_set_token)
    monkeypatch.setattr(clients_router, "get_client_shopify_connection_status", fake_status)

    response = api_client.patch(
        f"/clients/{client_id}/shopify/installation",
        json={
            "shopDomain": "example.myshopify.com",
            "storefrontAccessToken": "shptka_123",
        },
    )

    assert response.status_code == 200
    assert observed == {
        "client_id": client_id,
        "shop_domain": "example.myshopify.com",
        "storefront_access_token": "shptka_123",
    }
    assert response.json()["state"] == "installed_missing_storefront_token"


def test_auto_provision_shopify_installation_storefront_token_returns_status(
    api_client, monkeypatch
):
    client_id = _create_client(api_client)

    observed: dict[str, str] = {}

    def fake_auto_provision(*, client_id: str, shop_domain: str) -> None:
        observed["client_id"] = client_id
        observed["shop_domain"] = shop_domain

    def fake_status(*, client_id: str, selected_shop_domain: str | None = None):
        return {
            "state": "ready",
            "message": "Shopify connection is ready.",
            "shopDomain": "example.myshopify.com",
            "shopDomains": ["example.myshopify.com"],
            "selectedShopDomain": selected_shop_domain,
            "hasStorefrontAccessToken": True,
            "missingScopes": [],
        }

    monkeypatch.setattr(
        clients_router,
        "auto_provision_client_shopify_storefront_token",
        fake_auto_provision,
    )
    monkeypatch.setattr(clients_router, "get_client_shopify_connection_status", fake_status)

    response = api_client.post(
        f"/clients/{client_id}/shopify/installation/auto-storefront-token",
        json={"shopDomain": "example.myshopify.com"},
    )

    assert response.status_code == 200
    assert observed == {
        "client_id": client_id,
        "shop_domain": "example.myshopify.com",
    }
    assert response.json()["state"] == "ready"


def test_disconnect_shopify_installation_unlinks_workspace_and_returns_status(
    api_client, monkeypatch
):
    client_id = _create_client(api_client)

    observed: dict[str, str] = {}

    def fake_disconnect(*, client_id: str, shop_domain: str) -> None:
        observed["client_id"] = client_id
        observed["shop_domain"] = shop_domain

    def fake_status(*, client_id: str, selected_shop_domain: str | None = None):
        return {
            "state": "not_connected",
            "message": "Shopify is not connected for this workspace.",
            "shopDomain": None,
            "shopDomains": [],
            "selectedShopDomain": selected_shop_domain,
            "hasStorefrontAccessToken": False,
            "missingScopes": [],
        }

    monkeypatch.setattr(clients_router, "disconnect_client_shopify_store", fake_disconnect)
    monkeypatch.setattr(clients_router, "get_client_shopify_connection_status", fake_status)

    response = api_client.request(
        method="DELETE",
        url=f"/clients/{client_id}/shopify/installation",
        json={"shopDomain": "example.myshopify.com"},
    )

    assert response.status_code == 200
    assert observed == {
        "client_id": client_id,
        "shop_domain": "example.myshopify.com",
    }
    assert response.json()["state"] == "not_connected"


def test_list_shopify_products_returns_products(api_client, monkeypatch):
    client_id = _create_client(api_client)

    observed: dict[str, object] = {}

    def fake_list(*, client_id: str, query: str | None, limit: int, shop_domain: str | None):
        observed["client_id"] = client_id
        observed["query"] = query
        observed["limit"] = limit
        observed["shop_domain"] = shop_domain
        return {
            "shopDomain": "example.myshopify.com",
            "products": [
                {
                    "productGid": "gid://shopify/Product/123",
                    "title": "Sleep Drops",
                    "handle": "sleep-drops",
                    "status": "ACTIVE",
                }
            ],
        }

    monkeypatch.setattr(clients_router, "list_client_shopify_products", fake_list)

    response = api_client.get(
        f"/clients/{client_id}/shopify/products",
        params={"query": "sleep", "limit": 10, "shopDomain": "example.myshopify.com"},
    )

    assert response.status_code == 200
    assert observed == {
        "client_id": client_id,
        "query": "sleep",
        "limit": 10,
        "shop_domain": "example.myshopify.com",
    }
    payload = response.json()
    assert payload["shopDomain"] == "example.myshopify.com"
    assert payload["products"][0]["productGid"] == "gid://shopify/Product/123"


def test_set_default_shop_updates_status(api_client, monkeypatch):
    client_id = _create_client(api_client)

    def fake_installations():
        return [
            ShopifyInstallation(
                shop_domain="one.myshopify.com",
                client_id=client_id,
                has_storefront_access_token=True,
                scopes=[],
                uninstalled_at=None,
            )
        ]

    def fake_status(*, client_id: str, selected_shop_domain: str | None = None):
        assert client_id
        return {
            "state": "ready",
            "message": "Shopify connection is ready.",
            "shopDomain": selected_shop_domain,
            "shopDomains": [],
            "selectedShopDomain": selected_shop_domain,
            "hasStorefrontAccessToken": True,
            "missingScopes": [],
        }

    monkeypatch.setattr(clients_router, "list_shopify_installations", fake_installations)
    monkeypatch.setattr(clients_router, "get_client_shopify_connection_status", fake_status)

    response = api_client.put(
        f"/clients/{client_id}/shopify/default-shop",
        json={"shopDomain": "one.myshopify.com"},
    )

    assert response.status_code == 200
    body = response.json()
    assert body["state"] == "ready"
    assert body["selectedShopDomain"] == "one.myshopify.com"


def test_create_shopify_product_returns_created_payload(api_client, monkeypatch):
    client_id = _create_client(api_client)
    observed: dict[str, object] = {}

    def fake_status(*, client_id: str, selected_shop_domain: str | None = None):
        return {
            "state": "ready",
            "message": "Shopify connection is ready.",
            "shopDomain": selected_shop_domain or "example.myshopify.com",
            "shopDomains": [],
            "selectedShopDomain": selected_shop_domain,
            "hasStorefrontAccessToken": True,
            "missingScopes": [],
        }

    def fake_create(
        *,
        client_id: str,
        title: str,
        variants: list[dict],
        description: str | None,
        handle: str | None,
        vendor: str | None,
        product_type: str | None,
        tags: list[str] | None,
        status_text: str,
        shop_domain: str | None,
    ):
        observed["client_id"] = client_id
        observed["title"] = title
        observed["variants"] = variants
        observed["shop_domain"] = shop_domain
        return {
            "shopDomain": "example.myshopify.com",
            "productGid": "gid://shopify/Product/900",
            "title": "Sleep Drops",
            "handle": "sleep-drops",
            "status": "DRAFT",
            "variants": [
                {
                    "variantGid": "gid://shopify/ProductVariant/901",
                    "title": "Starter",
                    "priceCents": 4999,
                    "currency": "USD",
                }
            ],
        }

    monkeypatch.setattr(clients_router, "get_client_shopify_connection_status", fake_status)
    monkeypatch.setattr(clients_router, "create_client_shopify_product", fake_create)

    response = api_client.post(
        f"/clients/{client_id}/shopify/products",
        json={
            "title": "Sleep Drops",
            "status": "DRAFT",
            "variants": [{"title": "Starter", "priceCents": 4999, "currency": "USD"}],
        },
    )

    assert response.status_code == 200
    assert observed["client_id"] == client_id
    assert observed["title"] == "Sleep Drops"
    assert observed["shop_domain"] is None
    payload = response.json()
    assert payload["productGid"] == "gid://shopify/Product/900"
    assert payload["variants"][0]["variantGid"] == "gid://shopify/ProductVariant/901"


def test_create_shopify_product_requires_ready_connection(api_client, monkeypatch):
    client_id = _create_client(api_client)

    def fake_status(*, client_id: str, selected_shop_domain: str | None = None):
        return {
            "state": "installed_missing_storefront_token",
            "message": "Shopify is installed but missing storefront access token.",
            "shopDomain": "example.myshopify.com",
            "shopDomains": [],
            "selectedShopDomain": selected_shop_domain,
            "hasStorefrontAccessToken": False,
            "missingScopes": [],
        }

    monkeypatch.setattr(clients_router, "get_client_shopify_connection_status", fake_status)

    response = api_client.post(
        f"/clients/{client_id}/shopify/products",
        json={
            "title": "Sleep Drops",
            "status": "DRAFT",
            "variants": [{"title": "Starter", "priceCents": 4999, "currency": "USD"}],
        },
    )

    assert response.status_code == 409


def test_enqueue_shopify_theme_brand_sync_job_is_disabled(api_client, monkeypatch):
    client_id = _create_client(api_client, name="Acme Workspace")
    observed: dict[str, object] = {}

    def fake_run_sync_job(job_id: str):
        observed["job_id"] = job_id

    monkeypatch.setattr(
        clients_router,
        "_run_client_shopify_theme_brand_sync_job",
        fake_run_sync_job,
    )

    response = api_client.post(
        f"/clients/{client_id}/shopify/theme/brand/sync-async",
        json={
            "shopDomain": "example.myshopify.com",
            "designSystemId": "design-system-1",
            "themeName": "futrgroup2-0theme",
        },
    )

    assert response.status_code == 409
    assert "Direct Shopify theme sync is disabled." in response.json()["detail"]


def test_enqueue_shopify_theme_template_build_job_returns_accepted(api_client, monkeypatch):
    client_id = _create_client(api_client, name="Acme Workspace")
    observed: dict[str, object] = {}

    def fake_run_build_job(job_id: str):
        observed["job_id"] = job_id

    monkeypatch.setattr(
        clients_router,
        "_run_client_shopify_theme_template_build_job",
        fake_run_build_job,
    )

    response = api_client.post(
        f"/clients/{client_id}/shopify/theme/brand/template/build-async",
        json={
            "shopDomain": "example.myshopify.com",
            "designSystemId": "design-system-1",
        },
    )

    assert response.status_code == 202
    payload = response.json()
    assert isinstance(payload["jobId"], str) and payload["jobId"]
    assert payload["status"] in {"queued", "running", "succeeded", "failed"}
    assert payload["statusPath"] == (
        f"/clients/{client_id}/shopify/theme/brand/template/build-jobs/{payload['jobId']}"
    )
    assert observed["job_id"] == payload["jobId"]

    status_response = api_client.get(
        f"/clients/{client_id}/shopify/theme/brand/template/build-jobs/{payload['jobId']}"
    )
    assert status_response.status_code == 200
    status_payload = status_response.json()
    assert status_payload["jobId"] == payload["jobId"]
    assert status_payload["status"] in {"queued", "running", "succeeded", "failed"}


def test_enqueue_shopify_theme_template_publish_job_is_disabled(api_client, monkeypatch):
    client_id = _create_client(api_client, name="Acme Workspace")
    observed: dict[str, object] = {}

    def fake_run_publish_job(job_id: str):
        observed["job_id"] = job_id

    monkeypatch.setattr(
        clients_router,
        "_run_client_shopify_theme_template_publish_job",
        fake_run_publish_job,
    )

    response = api_client.post(
        f"/clients/{client_id}/shopify/theme/brand/template/publish-async",
        json={"draftId": "draft-1"},
    )

    assert response.status_code == 409
    assert "Direct Shopify theme publish is disabled." in response.json()["detail"]


def test_update_shopify_theme_template_draft_creates_new_version(api_client, db_session, monkeypatch):
    client_id = _create_client(api_client, name="Acme Workspace")
    client = db_session.scalar(select(Client).where(Client.id == client_id))
    assert client is not None
    monkeypatch.setattr(
        clients_router.settings, "PUBLIC_ASSET_BASE_URL", "https://assets.example.com"
    )

    image_asset_public_id = uuid4()
    text_asset_public_id = uuid4()
    db_session.add(
        Asset(
            org_id=client.org_id,
            client_id=client.id,
            source_type=AssetSourceEnum.generated,
            channel_id="meta",
            format="image",
            content={"label": "image one"},
            public_id=image_asset_public_id,
            asset_kind="image",
        )
    )
    db_session.add(
        Asset(
            org_id=client.org_id,
            client_id=client.id,
            source_type=AssetSourceEnum.generated,
            channel_id="meta",
            format="image",
            content={"label": "image two"},
            public_id=text_asset_public_id,
            asset_kind="image",
        )
    )

    draft = ShopifyThemeTemplateDraft(
        org_id=client.org_id,
        client_id=client.id,
        design_system_id=None,
        product_id=None,
        shop_domain="example.myshopify.com",
        theme_id="gid://shopify/OnlineStoreTheme/123",
        theme_name="legacy-theme-name",
        theme_role="MAIN",
        status="draft",
        created_by_user_external_id="test-user",
        created_at=datetime.now(timezone.utc),
        updated_at=datetime.now(timezone.utc),
    )
    db_session.add(draft)
    db_session.flush()
    version = ShopifyThemeTemplateDraftVersion(
        draft_id=draft.id,
        org_id=client.org_id,
        client_id=client.id,
        version_number=1,
        source="build_job",
        payload={
            "shopDomain": "example.myshopify.com",
            "workspaceName": "Acme Workspace",
            "designSystemId": "design-system-1",
            "designSystemName": "Acme DS",
            "brandName": "Draft Snapshot Brand",
            "logoAssetPublicId": str(uuid4()),
            "logoUrl": "https://assets.example.com/public/assets/logo-1",
            "themeId": "gid://shopify/OnlineStoreTheme/123",
            "themeName": "legacy-theme-name",
            "themeRole": "MAIN",
            "cssVars": {"--color-brand": "#123456"},
            "fontUrls": [],
            "dataTheme": "light",
            "productId": None,
            "componentImageAssetMap": {
                "templates/index.json.sections.hero.settings.image": str(image_asset_public_id)
            },
            "componentTextValues": {
                "templates/index.json.sections.hero.settings.heading": "Old heading"
            },
            "imageSlots": [],
            "textSlots": [],
            "metadata": {},
        },
        created_by_user_external_id="test-user",
        created_at=datetime.now(timezone.utc),
    )
    db_session.add(version)
    db_session.commit()

    list_response = api_client.get(f"/clients/{client_id}/shopify/theme/brand/template/drafts")
    assert list_response.status_code == 200
    list_payload = list_response.json()
    assert len(list_payload) == 1
    assert list_payload[0]["id"] == str(draft.id)
    assert list_payload[0]["latestVersion"]["versionNumber"] == 1

    update_response = api_client.put(
        f"/clients/{client_id}/shopify/theme/brand/template/drafts/{draft.id}",
        json={
            "componentImageAssetMap": {
                "templates/index.json.sections.hero.settings.image": str(text_asset_public_id)
            },
            "componentTextValues": {
                "templates/index.json.sections.hero.settings.heading": "New heading"
            },
            "notes": "Updated hero creative",
        },
    )
    assert update_response.status_code == 200
    update_payload = update_response.json()
    assert update_payload["id"] == str(draft.id)
    assert update_payload["latestVersion"]["versionNumber"] == 2
    assert update_payload["latestVersion"]["source"] == "manual_edit"
    assert update_payload["latestVersion"]["data"]["componentImageAssetMap"] == {
        "templates/index.json.sections.hero.settings.image": str(text_asset_public_id)
    }
    assert update_payload["latestVersion"]["data"]["componentTextValues"] == {
        "templates/index.json.sections.hero.settings.heading": "New heading"
    }


def test_export_shopify_theme_template_zip_returns_archive(api_client, db_session, monkeypatch):
    client_id = _create_client(api_client, name="Acme Workspace")
    client = db_session.scalar(select(Client).where(Client.id == client_id))
    assert client is not None
    monkeypatch.setattr(
        clients_router.settings, "PUBLIC_ASSET_BASE_URL", "https://assets.example.com"
    )

    image_asset_public_id = uuid4()
    db_session.add(
        Asset(
            org_id=client.org_id,
            client_id=client.id,
            source_type=AssetSourceEnum.generated,
            channel_id="meta",
            format="image",
            content={"label": "hero image"},
            public_id=image_asset_public_id,
            asset_kind="image",
        )
    )
    draft = ShopifyThemeTemplateDraft(
        org_id=client.org_id,
        client_id=client.id,
        design_system_id=None,
        product_id=None,
        shop_domain="example.myshopify.com",
        theme_id="gid://shopify/OnlineStoreTheme/123",
        theme_name="legacy-theme-name",
        theme_role="MAIN",
        status="draft",
        created_by_user_external_id="test-user",
        created_at=datetime.now(timezone.utc),
        updated_at=datetime.now(timezone.utc),
    )
    db_session.add(draft)
    db_session.flush()
    version = ShopifyThemeTemplateDraftVersion(
        draft_id=draft.id,
        org_id=client.org_id,
        client_id=client.id,
        version_number=4,
        source="build_job",
        payload={
            "shopDomain": "example.myshopify.com",
            "workspaceName": "Acme Workspace",
            "designSystemId": "design-system-1",
            "designSystemName": "Acme DS",
            "brandName": "Acme",
            "logoAssetPublicId": str(uuid4()),
            "logoUrl": "https://assets.example.com/public/assets/logo-1",
            "themeId": "gid://shopify/OnlineStoreTheme/123",
            "themeName": "updated-theme-name",
            "themeRole": "MAIN",
            "cssVars": {"--color-brand": "#123456"},
            "fontUrls": [],
            "dataTheme": "light",
            "productId": None,
            "componentImageAssetMap": {
                "templates/collection.json.sections.main-collection.blocks.promotion.settings.image": str(
                    image_asset_public_id
                )
            },
            "componentTextValues": {
                "templates/collection.json.sections.main-collection.blocks.promotion.settings.heading": "Glow brighter"
            },
            "imageSlots": [],
            "textSlots": [],
            "metadata": {},
        },
        created_by_user_external_id="test-user",
        created_at=datetime.now(timezone.utc),
    )
    db_session.add(version)
    db_session.commit()

    def fake_status(*, client_id: str, selected_shop_domain: str | None = None):
        return {
            "state": "ready",
            "message": "Shopify connection is ready.",
            "shopDomain": selected_shop_domain or "example.myshopify.com",
            "shopDomains": [],
            "selectedShopDomain": selected_shop_domain,
            "hasStorefrontAccessToken": True,
            "missingScopes": [],
        }

    def fake_list_theme_template_slots(
        *,
        client_id: str,
        theme_id: str | None = None,
        theme_name: str | None = None,
        shop_domain: str | None = None,
    ):
        assert client_id
        assert theme_id == "gid://shopify/OnlineStoreTheme/123"
        assert theme_name is None
        assert shop_domain == "example.myshopify.com"
        return {
            "shopDomain": "example.myshopify.com",
            "themeId": "gid://shopify/OnlineStoreTheme/123",
            "themeName": "updated-theme-name",
            "themeRole": "MAIN",
            "imageSlots": [
                {
                    "path": "templates/collection.json.sections.main-collection.blocks.promotion.settings.image",
                    "key": "image",
                    "role": "supporting",
                    "recommendedAspect": "landscape",
                    "currentValue": None,
                }
            ],
            "textSlots": [
                {
                    "path": "templates/collection.json.sections.main-collection.blocks.promotion.settings.heading",
                    "key": "heading",
                    "currentValue": None,
                }
            ],
        }

    def fake_export_theme_brand(
        *,
        client_id: str,
        workspace_name: str,
        brand_name: str,
        logo_url: str,
        css_vars: dict[str, str],
        font_urls: list[str] | None,
        data_theme: str | None,
        component_image_urls: dict[str, str] | None,
        component_text_values: dict[str, str] | None,
        auto_component_image_urls: list[str] | None,
        theme_id: str | None,
        theme_name: str | None,
        shop_domain: str | None,
    ):
        assert workspace_name == "Acme Workspace"
        assert brand_name == "Latest Brand Name"
        assert logo_url == "https://assets.example.com/public/assets/latest-logo"
        assert css_vars == {
            "--color-brand": "#654321",
            "--footer-text-color": "#010203",
            "--announcement-text-color": "#fefefe",
        }
        assert font_urls == [
            "https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap"
        ]
        assert data_theme == "dark"
        assert theme_id == "gid://shopify/OnlineStoreTheme/123"
        assert theme_name is None
        assert shop_domain == "example.myshopify.com"
        assert component_image_urls is not None
        assert component_text_values is not None
        return {
            "shopDomain": "example.myshopify.com",
            "themeId": "gid://shopify/OnlineStoreTheme/123",
            "themeName": "updated-theme-name",
            "themeRole": "MAIN",
            "layoutFilename": "layout/theme.liquid",
            "cssFilename": "assets/acme-workspace-workspace-brand.css",
            "settingsFilename": "config/settings_data.json",
            "jobId": None,
            "coverage": {
                "requiredSourceVars": [],
                "requiredThemeVars": [],
                "missingSourceVars": [],
                "missingThemeVars": [],
            },
            "settingsSync": {
                "settingsFilename": "config/settings_data.json",
                "expectedPaths": [],
                "updatedPaths": [],
                "missingPaths": [],
                "requiredMissingPaths": [],
                "semanticUpdatedPaths": [],
                "unmappedColorPaths": [],
                "semanticTypographyUpdatedPaths": [],
                "unmappedTypographyPaths": [],
            },
            "files": [
                {
                    "filename": "layout/theme.liquid",
                    "content": "{% comment %}Managed by mOS{% endcomment %}",
                },
                {
                    "filename": "assets/acme-workspace-workspace-brand.css",
                    "content": ":root { --color-brand: #123456; }",
                },
                {
                    "filename": "templates/index.json",
                    "content": (
                        '{"sections":{"hero":{"settings":{"button_link":"/collections/test"}}}}'
                    ),
                },
                {
                    "filename": "templates/collection.json",
                    "content": (
                        '{"sections":{"main-collection-banner":{"type":"main-collection-banner"},'
                        '"main-collection":{"blocks":{"promotion":{"settings":'
                        '{"image":"shopify://shop_images/promo-uploaded.png","heading":"<p>Glow brighter</p>"}}}}}}'
                    ),
                },
                {
                    "filename": "templates/list-collections.json",
                    "content": (
                        '{"sections":{"main":{"type":"main-list-collections"}},"order":["main"]}'
                    ),
                },
                {
                    "filename": "snippets/header-drawer.liquid",
                    "content": (
                        '<ul role="list"><li><a href="/">Home</a></li>'
                        '<li><details is="menu-details">'
                        '<summary aria-expanded="false">Catalog</summary>'
                        '<div><button type="button">Catalog</button></div>'
                        '<ul><li><a href="/collections/test">Test 1</a></li>'
                        '<li><a href="/collections/test">Test 2</a></li></ul>'
                        "</details></li>"
                        '<li><a href="/pages/contact">Contact</a></li></ul>'
                    ),
                },
            ],
        }

    def fake_sync_compliance_for_export(
        *,
        client_id: str,
        shop_domain: str | None,
        auth,
        session,
    ):
        assert client_id
        assert shop_domain == "example.myshopify.com"
        assert auth.user_id == "test-user"
        assert session is not None
        return {
            "rulesetVersion": "meta_tiktok_compliance_ruleset_v1",
            "shopDomain": "example.myshopify.com",
            "pages": [
                {
                    "pageKey": "privacy_policy",
                    "pageId": "gid://shopify/Page/101",
                    "title": "Privacy Policy",
                    "handle": "privacy-policy",
                    "url": "https://example.myshopify.com/pages/privacy-policy",
                    "operation": "created",
                }
            ],
            "updatedProfileUrls": {
                "privacy_policy_url": "https://example.myshopify.com/pages/privacy-policy"
            },
            "renderedPages": [
                {
                    "pageKey": "privacy_policy",
                    "title": "Privacy Policy",
                    "handle": "privacy-policy",
                    "markdown": "# Privacy Policy\n\nGenerated copy.",
                    "url": "https://example.myshopify.com/pages/privacy-policy",
                }
            ],
        }

    def fake_resolve_latest_snapshot(
        *,
        session,
        org_id: str,
        client_id: str,
        design_system_id: str,
    ):
        assert session is not None
        assert org_id == str(client.org_id)
        assert client_id
        assert design_system_id == "design-system-1"
        return (
            "Latest Brand Name",
            "latest-logo",
            "https://assets.example.com/public/assets/latest-logo",
            {
                "--color-brand": "#654321",
                "--footer-text-color": "#010203",
                "--announcement-text-color": "#fefefe",
            },
            [
                "https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap"
            ],
            "dark",
        )

    monkeypatch.setattr(clients_router, "get_client_shopify_connection_status", fake_status)
    monkeypatch.setattr(
        clients_router,
        "list_client_shopify_theme_template_slots",
        fake_list_theme_template_slots,
    )
    monkeypatch.setattr(clients_router, "export_client_shopify_theme_brand", fake_export_theme_brand)
    monkeypatch.setattr(
        clients_router,
        "_resolve_latest_template_publish_design_system_snapshot",
        fake_resolve_latest_snapshot,
    )
    monkeypatch.setattr(
        clients_router,
        "_sync_compliance_policy_pages_for_template_export",
        fake_sync_compliance_for_export,
    )

    response = api_client.post(
        f"/clients/{client_id}/shopify/theme/brand/template/export-zip",
        json={"draftId": str(draft.id)},
    )

    assert response.status_code == 200
    assert response.headers["content-type"] == "application/zip"
    assert "attachment; filename=" in response.headers["content-disposition"]
    assert (
        response.headers["content-disposition"]
        == 'attachment; filename="updated-theme-name.zip"'
    )

    archive = zipfile.ZipFile(io.BytesIO(response.content))
    namelist = sorted(archive.namelist())
    assert "assets/acme-workspace-workspace-brand.css" in namelist
    assert "layout/theme.liquid" in namelist
    assert "templates/index.json" in namelist
    assert "snippets/header-drawer.liquid" in namelist
    assert "mos-template-export/manifest.json" in namelist
    assert "mos-template-export/policies/privacy-policy.md" in namelist
    exported_header_drawer = archive.read("snippets/header-drawer.liquid").decode("utf-8")
    assert "/collections/test" not in exported_header_drawer
    assert 'href="/collections/all"' in exported_header_drawer
    exported_index_template = archive.read("templates/index.json").decode("utf-8")
    assert "/collections/test" not in exported_index_template
    assert "/collections/all" in exported_index_template
    exported_collection_template = json.loads(
        archive.read("templates/collection.json").decode("utf-8")
    )
    assert (
        exported_collection_template["sections"]["main-collection"]["blocks"]["promotion"][
            "settings"
        ]["heading"]
        == "<p>Glow brighter</p>"
    )
    assert (
        exported_collection_template["sections"]["main-collection"]["blocks"]["promotion"][
            "settings"
        ]["image"]
        == "shopify://shop_images/promo-uploaded.png"
    )

    manifest = json.loads(archive.read("mos-template-export/manifest.json").decode("utf-8"))
    assert manifest["draftId"] == str(draft.id)
    assert isinstance(manifest.get("draftVersionId"), str)
    assert manifest["draftVersionId"].strip()
    assert manifest["shopDomain"] == "example.myshopify.com"
    assert manifest["themeName"] == "updated-theme-name"
    assert manifest["exportedFiles"] == [
        "layout/theme.liquid",
        "assets/acme-workspace-workspace-brand.css",
        "templates/index.json",
        "templates/collection.json",
        "templates/list-collections.json",
        "snippets/header-drawer.liquid",
    ]
    assert manifest["rewrittenCollectionLinks"] == {
        "totalReplacements": 3,
        "filesByName": {
            "templates/index.json": 1,
            "snippets/header-drawer.liquid": 2,
        },
    }
    assert manifest["collectionTemplateValidation"] == {
        "validatedImagePaths": [
            "templates/collection.json.sections.main-collection.blocks.promotion.settings.image"
        ],
        "validatedTextPaths": [
            "templates/collection.json.sections.main-collection.blocks.promotion.settings.heading"
        ],
    }
    assert manifest["compliancePolicyFiles"] == [
        "mos-template-export/policies/privacy-policy.md"
    ]
    assert manifest["compliancePolicySync"]["rulesetVersion"] == "meta_tiktok_compliance_ruleset_v1"
    assert manifest["compliancePolicySync"]["shopDomain"] == "example.myshopify.com"

    db_session.expire_all()
    refreshed_draft = db_session.scalar(
        select(ShopifyThemeTemplateDraft).where(ShopifyThemeTemplateDraft.id == draft.id)
    )
    assert refreshed_draft is not None
    assert refreshed_draft.theme_name == "updated-theme-name"
    latest_version = db_session.scalar(
        select(ShopifyThemeTemplateDraftVersion)
        .where(ShopifyThemeTemplateDraftVersion.draft_id == draft.id)
        .order_by(ShopifyThemeTemplateDraftVersion.version_number.desc())
    )
    assert latest_version is not None
    assert manifest["draftVersionId"] == str(latest_version.id)
    assert latest_version.payload["themeName"] == "updated-theme-name"


def test_export_shopify_theme_template_zip_writes_base64_file_payloads(
    api_client, db_session, monkeypatch
):
    client_id = _create_client(api_client, name="Acme Workspace")
    client = db_session.scalar(select(Client).where(Client.id == client_id))
    assert client is not None

    draft = ShopifyThemeTemplateDraft(
        org_id=client.org_id,
        client_id=client.id,
        design_system_id=None,
        product_id=None,
        shop_domain="example.myshopify.com",
        theme_id="gid://shopify/OnlineStoreTheme/123",
        theme_name="futrgroup2-0theme",
        theme_role="MAIN",
        status="draft",
        created_by_user_external_id="test-user",
        created_at=datetime.now(timezone.utc),
        updated_at=datetime.now(timezone.utc),
    )
    db_session.add(draft)
    db_session.flush()
    version = ShopifyThemeTemplateDraftVersion(
        draft_id=draft.id,
        org_id=client.org_id,
        client_id=client.id,
        version_number=1,
        source="build_job",
        payload={
            "shopDomain": "example.myshopify.com",
            "workspaceName": "Acme Workspace",
            "designSystemId": "design-system-1",
            "designSystemName": "Acme DS",
            "brandName": "Draft Snapshot Brand",
            "logoAssetPublicId": str(uuid4()),
            "logoUrl": "https://assets.example.com/public/assets/logo-1",
            "themeId": "gid://shopify/OnlineStoreTheme/123",
            "themeName": "futrgroup2-0theme",
            "themeRole": "MAIN",
            "cssVars": {"--color-brand": "#123456"},
            "fontUrls": [],
            "dataTheme": "light",
            "productId": None,
            "componentImageAssetMap": {},
            "componentTextValues": {},
            "imageSlots": [],
            "textSlots": [],
            "metadata": {},
        },
        created_by_user_external_id="test-user",
        created_at=datetime.now(timezone.utc),
    )
    db_session.add(version)
    db_session.commit()

    binary_asset = b"\x89PNG\r\n\x1a\n\x00\x00\x00IHDR\x00\x00"

    def fake_status(*, client_id: str, selected_shop_domain: str | None = None):
        return {
            "state": "ready",
            "message": "Shopify connection is ready.",
            "shopDomain": selected_shop_domain or "example.myshopify.com",
            "shopDomains": [],
            "selectedShopDomain": selected_shop_domain,
            "hasStorefrontAccessToken": True,
            "missingScopes": [],
        }

    def fake_list_theme_template_slots(
        *,
        client_id: str,
        theme_id: str | None = None,
        theme_name: str | None = None,
        shop_domain: str | None = None,
    ):
        assert client_id
        assert theme_id == "gid://shopify/OnlineStoreTheme/123"
        assert theme_name is None
        assert shop_domain == "example.myshopify.com"
        return {
            "shopDomain": "example.myshopify.com",
            "themeId": "gid://shopify/OnlineStoreTheme/123",
            "themeName": "futrgroup2-0theme",
            "themeRole": "MAIN",
            "imageSlots": [],
            "textSlots": [],
        }

    def fake_export_theme_brand(
        *,
        client_id: str,
        workspace_name: str,
        brand_name: str,
        logo_url: str,
        css_vars: dict[str, str],
        font_urls: list[str] | None,
        data_theme: str | None,
        component_image_urls: dict[str, str] | None,
        component_text_values: dict[str, str] | None,
        auto_component_image_urls: list[str] | None,
        theme_id: str | None,
        theme_name: str | None,
        shop_domain: str | None,
    ):
        assert brand_name == "Latest Brand Name"
        assert logo_url == "https://assets.example.com/public/assets/latest-logo"
        assert css_vars == {"--color-brand": "#654321"}
        assert font_urls == [
            "https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap"
        ]
        assert data_theme == "dark"
        return {
            "shopDomain": "example.myshopify.com",
            "themeId": "gid://shopify/OnlineStoreTheme/123",
            "themeName": "futrgroup2-0theme",
            "themeRole": "MAIN",
            "layoutFilename": "layout/theme.liquid",
            "cssFilename": "assets/acme-workspace-workspace-brand.css",
            "settingsFilename": "config/settings_data.json",
            "jobId": None,
            "coverage": {
                "requiredSourceVars": [],
                "requiredThemeVars": [],
                "missingSourceVars": [],
                "missingThemeVars": [],
            },
            "settingsSync": {
                "settingsFilename": "config/settings_data.json",
                "expectedPaths": [],
                "updatedPaths": [],
                "missingPaths": [],
                "requiredMissingPaths": [],
                "semanticUpdatedPaths": [],
                "unmappedColorPaths": [],
                "semanticTypographyUpdatedPaths": [],
                "unmappedTypographyPaths": [],
            },
            "files": [
                {
                    "filename": "layout/theme.liquid",
                    "content": "{% comment %}Managed by mOS{% endcomment %}",
                },
                {
                    "filename": "templates/collection.json",
                    "content": json.dumps(
                        {
                            "sections": {
                                "main-collection-banner": {
                                    "type": "main-collection-banner"
                                },
                                "main-collection": {"type": "main-collection"},
                            }
                        }
                    ),
                },
                {
                    "filename": "templates/list-collections.json",
                    "content": json.dumps(
                        {
                            "sections": {
                                "main": {"type": "main-list-collections"}
                            },
                            "order": ["main"],
                        }
                    ),
                },
                {
                    "filename": "assets/hero.png",
                    "contentBase64": base64.b64encode(binary_asset).decode("ascii"),
                },
            ],
        }

    def fake_sync_compliance_for_export(
        *,
        client_id: str,
        shop_domain: str | None,
        auth,
        session,
    ):
        return {
            "rulesetVersion": "meta_tiktok_compliance_ruleset_v1",
            "shopDomain": "example.myshopify.com",
            "pages": [],
            "updatedProfileUrls": {},
            "renderedPages": [],
        }

    def fake_resolve_latest_snapshot(
        *,
        session,
        org_id: str,
        client_id: str,
        design_system_id: str,
    ):
        assert session is not None
        assert org_id == str(client.org_id)
        assert client_id
        assert design_system_id == "design-system-1"
        return (
            "Latest Brand Name",
            "latest-logo",
            "https://assets.example.com/public/assets/latest-logo",
            {"--color-brand": "#654321"},
            [
                "https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap"
            ],
            "dark",
        )

    monkeypatch.setattr(clients_router, "get_client_shopify_connection_status", fake_status)
    monkeypatch.setattr(
        clients_router,
        "list_client_shopify_theme_template_slots",
        fake_list_theme_template_slots,
    )
    monkeypatch.setattr(
        clients_router, "export_client_shopify_theme_brand", fake_export_theme_brand
    )
    monkeypatch.setattr(
        clients_router,
        "_resolve_latest_template_publish_design_system_snapshot",
        fake_resolve_latest_snapshot,
    )
    monkeypatch.setattr(
        clients_router,
        "_sync_compliance_policy_pages_for_template_export",
        fake_sync_compliance_for_export,
    )

    response = api_client.post(
        f"/clients/{client_id}/shopify/theme/brand/template/export-zip",
        json={"draftId": str(draft.id)},
    )

    assert response.status_code == 200
    assert (
        response.headers["content-disposition"]
        == 'attachment; filename="futrgroup2-0theme.zip"'
    )
    archive = zipfile.ZipFile(io.BytesIO(response.content))
    assert "assets/hero.png" in archive.namelist()
    assert archive.read("assets/hero.png") == binary_asset


def test_export_shopify_theme_template_zip_refreshes_slot_snapshot_when_changed(
    api_client, db_session, monkeypatch
):
    client_id = _create_client(api_client, name="Acme Workspace")
    client = db_session.scalar(select(Client).where(Client.id == client_id))
    assert client is not None

    draft = ShopifyThemeTemplateDraft(
        org_id=client.org_id,
        client_id=client.id,
        design_system_id=None,
        product_id=None,
        shop_domain="example.myshopify.com",
        theme_id="gid://shopify/OnlineStoreTheme/123",
        theme_name="futrgroup2-0theme",
        theme_role="MAIN",
        status="draft",
        created_by_user_external_id="test-user",
        created_at=datetime.now(timezone.utc),
        updated_at=datetime.now(timezone.utc),
    )
    db_session.add(draft)
    db_session.flush()
    version = ShopifyThemeTemplateDraftVersion(
        draft_id=draft.id,
        org_id=client.org_id,
        client_id=client.id,
        version_number=1,
        source="build_job",
        payload={
            "shopDomain": "example.myshopify.com",
            "workspaceName": "Acme Workspace",
            "designSystemId": "design-system-1",
            "designSystemName": "Acme DS",
            "brandName": "Draft Snapshot Brand",
            "logoAssetPublicId": str(uuid4()),
            "logoUrl": "https://assets.example.com/public/assets/logo-1",
            "themeId": "gid://shopify/OnlineStoreTheme/123",
            "themeName": "futrgroup2-0theme",
            "themeRole": "MAIN",
            "cssVars": {"--color-brand": "#123456"},
            "fontUrls": [],
            "dataTheme": "light",
            "productId": None,
            "componentImageAssetMap": {},
            "componentTextValues": {},
            "imageSlots": [],
            "textSlots": [],
            "metadata": {},
        },
        created_by_user_external_id="test-user",
        created_at=datetime.now(timezone.utc),
    )
    db_session.add(version)
    db_session.commit()

    def fake_status(*, client_id: str, selected_shop_domain: str | None = None):
        return {
            "state": "ready",
            "message": "Shopify connection is ready.",
            "shopDomain": selected_shop_domain or "example.myshopify.com",
            "shopDomains": [],
            "selectedShopDomain": selected_shop_domain,
            "hasStorefrontAccessToken": True,
            "missingScopes": [],
        }

    def fake_list_theme_template_slots(
        *,
        client_id: str,
        theme_id: str | None = None,
        theme_name: str | None = None,
        shop_domain: str | None = None,
    ):
        assert client_id
        assert theme_id == "gid://shopify/OnlineStoreTheme/123"
        assert theme_name is None
        assert shop_domain == "example.myshopify.com"
        return {
            "shopDomain": "example.myshopify.com",
            "themeId": "gid://shopify/OnlineStoreTheme/123",
            "themeName": "futrgroup2-0theme",
            "themeRole": "MAIN",
            "imageSlots": [
                {
                    "path": "templates/collection.json.sections.main-collection.blocks.promotion.settings.image",
                    "key": "image",
                    "role": "supporting",
                    "recommendedAspect": "landscape",
                    "currentValue": None,
                }
            ],
            "textSlots": [
                {
                    "path": "templates/collection.json.sections.main-collection.blocks.promotion.settings.heading",
                    "key": "heading",
                    "role": "headline",
                    "maxLength": 120,
                    "currentValue": "Promo heading",
                }
            ],
        }

    def fake_export_theme_brand(
        *,
        client_id: str,
        workspace_name: str,
        brand_name: str,
        logo_url: str,
        css_vars: dict[str, str],
        font_urls: list[str] | None,
        data_theme: str | None,
        component_image_urls: dict[str, str] | None,
        component_text_values: dict[str, str] | None,
        auto_component_image_urls: list[str] | None,
        theme_id: str | None,
        theme_name: str | None,
        shop_domain: str | None,
    ):
        return {
            "shopDomain": "example.myshopify.com",
            "themeId": "gid://shopify/OnlineStoreTheme/123",
            "themeName": "futrgroup2-0theme",
            "themeRole": "MAIN",
            "layoutFilename": "layout/theme.liquid",
            "cssFilename": "assets/acme-workspace-workspace-brand.css",
            "settingsFilename": "config/settings_data.json",
            "jobId": None,
            "coverage": {
                "requiredSourceVars": [],
                "requiredThemeVars": [],
                "missingSourceVars": [],
                "missingThemeVars": [],
            },
            "settingsSync": {
                "settingsFilename": "config/settings_data.json",
                "expectedPaths": [],
                "updatedPaths": [],
                "missingPaths": [],
                "requiredMissingPaths": [],
                "semanticUpdatedPaths": [],
                "unmappedColorPaths": [],
                "semanticTypographyUpdatedPaths": [],
                "unmappedTypographyPaths": [],
            },
            "files": [
                {
                    "filename": "layout/theme.liquid",
                    "content": "{% comment %}Managed by mOS{% endcomment %}",
                },
                {
                    "filename": "templates/collection.json",
                    "content": (
                        '{"sections":{"main-collection-banner":{"type":"main-collection-banner"},'
                        '"main-collection":{"type":"main-collection"}}}'
                    ),
                },
                {
                    "filename": "templates/list-collections.json",
                    "content": (
                        '{"sections":{"main":{"type":"main-list-collections"}},"order":["main"]}'
                    ),
                },
            ],
        }

    def fake_sync_compliance_for_export(
        *,
        client_id: str,
        shop_domain: str | None,
        auth,
        session,
    ):
        return {
            "rulesetVersion": "meta_tiktok_compliance_ruleset_v1",
            "shopDomain": "example.myshopify.com",
            "pages": [],
            "updatedProfileUrls": {},
            "renderedPages": [],
        }

    def fake_resolve_latest_snapshot(
        *,
        session,
        org_id: str,
        client_id: str,
        design_system_id: str,
    ):
        return (
            "Latest Brand Name",
            "latest-logo",
            "https://assets.example.com/public/assets/latest-logo",
            {"--color-brand": "#654321"},
            [],
            "dark",
        )

    monkeypatch.setattr(clients_router, "get_client_shopify_connection_status", fake_status)
    monkeypatch.setattr(
        clients_router,
        "list_client_shopify_theme_template_slots",
        fake_list_theme_template_slots,
    )
    monkeypatch.setattr(
        clients_router, "export_client_shopify_theme_brand", fake_export_theme_brand
    )
    monkeypatch.setattr(
        clients_router,
        "_resolve_latest_template_publish_design_system_snapshot",
        fake_resolve_latest_snapshot,
    )
    monkeypatch.setattr(
        clients_router,
        "_sync_compliance_policy_pages_for_template_export",
        fake_sync_compliance_for_export,
    )

    response = api_client.post(
        f"/clients/{client_id}/shopify/theme/brand/template/export-zip",
        json={"draftId": str(draft.id)},
    )

    assert response.status_code == 200
    archive = zipfile.ZipFile(io.BytesIO(response.content))
    manifest = json.loads(archive.read("mos-template-export/manifest.json").decode("utf-8"))
    assert manifest["draftVersionNumber"] == 2

    latest_version = db_session.scalar(
        select(ShopifyThemeTemplateDraftVersion)
        .where(ShopifyThemeTemplateDraftVersion.draft_id == draft.id)
        .order_by(ShopifyThemeTemplateDraftVersion.version_number.desc())
        .limit(1)
    )
    assert latest_version is not None
    assert latest_version.source == "slot_refresh"
    payload = latest_version.payload
    assert isinstance(payload, dict)
    assert len(payload["imageSlots"]) == 1
    assert len(payload["textSlots"]) == 1


def test_sync_shopify_theme_brand_is_disabled(api_client):
    client_id = _create_client(api_client)

    response = api_client.post(
        f"/clients/{client_id}/shopify/theme/brand/sync",
        json={"themeName": "futrgroup2-0theme"},
    )

    assert response.status_code == 409
    assert "Direct Shopify theme sync is disabled" in response.json()["detail"]


def test_audit_shopify_theme_brand_returns_audit_payload(api_client, monkeypatch):
    client_id = _create_client(api_client, name="Acme Workspace")
    observed: dict[str, object] = {}

    def fake_status(*, client_id: str, selected_shop_domain: str | None = None):
        observed["status_client_id"] = client_id
        observed["selected_shop_domain"] = selected_shop_domain
        return {
            "state": "ready",
            "message": "Shopify connection is ready.",
            "shopDomain": selected_shop_domain or "example.myshopify.com",
            "shopDomains": [],
            "selectedShopDomain": selected_shop_domain,
            "hasStorefrontAccessToken": True,
            "missingScopes": [],
        }

    def fake_design_system_get(self, *, org_id: str, design_system_id: str):
        observed["design_system_id"] = design_system_id
        return type(
            "FakeDesignSystem",
            (),
            {
                "id": design_system_id,
                "name": "Acme Design System",
                "client_id": client_id,
                "tokens": {"placeholder": True},
            },
        )()

    def fake_validate(tokens):
        assert tokens == {"placeholder": True}
        return {
            "dataTheme": "light",
            "cssVars": {"--color-brand": "#123456"},
            "fontUrls": [],
            "brand": {"name": "Acme", "logoAssetPublicId": "logo-public-id"},
            "funnelDefaults": {"containerWidth": "lg"},
        }

    def fake_audit_theme_brand(
        *,
        client_id: str,
        workspace_name: str,
        css_vars: dict[str, str],
        data_theme: str | None,
        theme_id: str | None,
        theme_name: str | None,
        shop_domain: str | None,
    ):
        observed["audit_client_id"] = client_id
        observed["workspace_name"] = workspace_name
        observed["css_vars"] = css_vars
        observed["data_theme"] = data_theme
        observed["theme_id"] = theme_id
        observed["theme_name"] = theme_name
        observed["shop_domain"] = shop_domain
        return {
            "shopDomain": "example.myshopify.com",
            "themeId": "gid://shopify/OnlineStoreTheme/1",
            "themeName": "futrgroup2-0theme",
            "themeRole": "MAIN",
            "layoutFilename": "layout/theme.liquid",
            "cssFilename": "assets/acme-workspace-workspace-brand.css",
            "settingsFilename": "config/settings_data.json",
            "hasManagedMarkerBlock": True,
            "layoutIncludesManagedCssAsset": True,
            "managedCssAssetExists": True,
            "coverage": {
                "requiredSourceVars": [],
                "requiredThemeVars": [],
                "missingSourceVars": [],
                "missingThemeVars": [],
            },
            "settingsAudit": {
                "settingsFilename": "config/settings_data.json",
                "expectedPaths": [],
                "syncedPaths": [],
                "mismatchedPaths": [],
                "missingPaths": [],
                "requiredMissingPaths": [],
                "requiredMismatchedPaths": [],
            },
            "isReady": True,
        }

    monkeypatch.setattr(clients_router, "get_client_shopify_connection_status", fake_status)
    monkeypatch.setattr(clients_router.DesignSystemsRepository, "get", fake_design_system_get)
    monkeypatch.setattr(clients_router, "validate_design_system_tokens", fake_validate)
    monkeypatch.setattr(clients_router, "audit_client_shopify_theme_brand", fake_audit_theme_brand)

    response = api_client.post(
        f"/clients/{client_id}/shopify/theme/brand/audit",
        json={
            "shopDomain": "example.myshopify.com",
            "designSystemId": "design-system-1",
            "themeName": "futrgroup2-0theme",
        },
    )

    assert response.status_code == 200
    payload = response.json()
    assert payload["shopDomain"] == "example.myshopify.com"
    assert payload["themeName"] == "futrgroup2-0theme"
    assert payload["isReady"] is True
    assert observed["workspace_name"] == "Acme Workspace"
    assert observed["data_theme"] == "light"
    assert observed["shop_domain"] == "example.myshopify.com"


def test_audit_shopify_theme_brand_requires_ready_connection(api_client, monkeypatch):
    client_id = _create_client(api_client)

    def fake_status(*, client_id: str, selected_shop_domain: str | None = None):
        return {
            "state": "installed_missing_storefront_token",
            "message": "Shopify is installed but missing storefront access token.",
            "shopDomain": "example.myshopify.com",
            "shopDomains": [],
            "selectedShopDomain": selected_shop_domain,
            "hasStorefrontAccessToken": False,
            "missingScopes": [],
        }

    monkeypatch.setattr(clients_router, "get_client_shopify_connection_status", fake_status)

    response = api_client.post(
        f"/clients/{client_id}/shopify/theme/brand/audit",
        json={"designSystemId": "design-system-1", "themeName": "futrgroup2-0theme"},
    )

    assert response.status_code == 409
    assert "Shopify connection is not ready" in response.json()["detail"]


def test_shopify_routes_require_existing_client(api_client):
    missing_client_id = "00000000-0000-0000-0000-00000000abcd"

    status_response = api_client.get(f"/clients/{missing_client_id}/shopify/status")
    install_response = api_client.post(
        f"/clients/{missing_client_id}/shopify/install-url",
        json={"shopDomain": "example.myshopify.com"},
    )
    patch_response = api_client.patch(
        f"/clients/{missing_client_id}/shopify/installation",
        json={"shopDomain": "example.myshopify.com", "storefrontAccessToken": "token"},
    )
    auto_provision_response = api_client.post(
        f"/clients/{missing_client_id}/shopify/installation/auto-storefront-token",
        json={"shopDomain": "example.myshopify.com"},
    )
    disconnect_response = api_client.request(
        method="DELETE",
        url=f"/clients/{missing_client_id}/shopify/installation",
        json={"shopDomain": "example.myshopify.com"},
    )
    default_shop_response = api_client.put(
        f"/clients/{missing_client_id}/shopify/default-shop",
        json={"shopDomain": "example.myshopify.com"},
    )
    create_product_response = api_client.post(
        f"/clients/{missing_client_id}/shopify/products",
        json={
            "title": "Sleep Drops",
            "status": "DRAFT",
            "variants": [{"title": "Starter", "priceCents": 4999, "currency": "USD"}],
        },
    )
    sync_theme_brand_response = api_client.post(
        f"/clients/{missing_client_id}/shopify/theme/brand/sync",
        json={"designSystemId": "design-system-1", "themeName": "futrgroup2-0theme"},
    )
    audit_theme_brand_response = api_client.post(
        f"/clients/{missing_client_id}/shopify/theme/brand/audit",
        json={"designSystemId": "design-system-1", "themeName": "futrgroup2-0theme"},
    )

    assert status_response.status_code == 404
    assert install_response.status_code == 404
    assert patch_response.status_code == 404
    assert auto_provision_response.status_code == 404
    assert disconnect_response.status_code == 404
    assert default_shop_response.status_code == 404
    assert create_product_response.status_code == 404
    assert sync_theme_brand_response.status_code == 404
    assert audit_theme_brand_response.status_code == 404
