from __future__ import annotations


V2_STEP_STAGE0_BUILD = "v2-01"
V2_STEP_ASSET_DATA_INGESTION = "v2-02i"
V2_STEP_RESEARCH_PROCEED_HITL = "v2-02a"
V2_STEP_COMPETITOR_ASSETS_HITL = "v2-02b"
V2_STEP_HABITAT_STRATEGY = "v2-02"
V2_STEP_SCRAPE_VIRALITY = "v2-03"
V2_STEP_APIFY_COLLECTION = "v2-03b"
V2_STEP_APIFY_POSTPROCESS = "v2-03c"
# Backward-compatible alias for callers still referencing "ingestion".
V2_STEP_APIFY_INGESTION = V2_STEP_APIFY_POSTPROCESS
V2_STEP_HABITAT_SCORING = "v2-04"
V2_STEP_VOC_EXTRACTION_RAW = "v2-05a"
V2_STEP_VOC_EXTRACTION = "v2-05"
V2_STEP_ANGLE_SYNTHESIS = "v2-06"
V2_STEP_ANGLE_SELECTION_HITL = "v2-07"
V2_STEP_OFFER_PIPELINE = "v2-08"
V2_STEP_OFFER_DATA_READINESS = "v2-08a"
V2_STEP_OFFER_VARIANT_SCORING = "v2-08b"
V2_STEP_OFFER_WINNER_HITL = "v2-09"
V2_STEP_COPY_PIPELINE = "v2-10"
V2_STEP_FINAL_APPROVAL_HITL = "v2-11"


V2_STEP_SEQUENCE = [
    V2_STEP_STAGE0_BUILD,
    V2_STEP_ASSET_DATA_INGESTION,
    V2_STEP_RESEARCH_PROCEED_HITL,
    V2_STEP_COMPETITOR_ASSETS_HITL,
    V2_STEP_HABITAT_STRATEGY,
    V2_STEP_SCRAPE_VIRALITY,
    V2_STEP_APIFY_COLLECTION,
    V2_STEP_APIFY_POSTPROCESS,
    V2_STEP_HABITAT_SCORING,
    V2_STEP_VOC_EXTRACTION_RAW,
    V2_STEP_VOC_EXTRACTION,
    V2_STEP_ANGLE_SYNTHESIS,
    V2_STEP_ANGLE_SELECTION_HITL,
    V2_STEP_OFFER_PIPELINE,
    V2_STEP_OFFER_DATA_READINESS,
    V2_STEP_OFFER_VARIANT_SCORING,
    V2_STEP_OFFER_WINNER_HITL,
    V2_STEP_COPY_PIPELINE,
    V2_STEP_FINAL_APPROVAL_HITL,
]
